version: '3.7'

x-environment: &commonEnvironment
    DIR_MOUNT: "${DATA_DIR}"
    DATA_DIR: "/app/work/data"
    PROJECT_ID: "-1"
    MLCOACH_URL: "http://localhost:8062"
    DATA_CLINIC_URL: "http://localhost:8072"
    MLEX_COMPUTE_URL: ${MLEX_COMPUTE_URL}
    MLEX_CONTENT_URL: ${MLEX_CONTENT_URL}
    HOST_NICKNAME: "local"
    TILED_KEY: "${TILED_KEY}"
    DEFAULT_TILED_URI: "${DEFAULT_TILED_URI}"
    APP_HOST: "0.0.0.0"
    APP_PORT: "8050"

services:

  labelmaker:
    container_name: "labelmaker"
    image: ghcr.io/mlexchange/mlex_labelmaker:main
    environment:
      *commonEnvironment
    volumes:
      - $DATA_DIR:/app/work/data
    ports:
      - 127.0.0.1:8057:8050
    networks:
      - computing_api_default

  mlcoach:
    container_name: "mlcoach"
    image: ghcr.io/mlexchange/mlex_mlcoach:main
    environment:
      *commonEnvironment
    volumes:
      - $DATA_DIR:/app/work/data
    ports:
      - 127.0.0.1:8062:8050
    networks:
      - computing_api_default

  data_clinic:
    container_name: "data_clinic"
    image: ghcr.io/mlexchange/mlex_data_clinic:master
    environment:
      *commonEnvironment
    volumes:
      - $DATA_DIR:/app/work/data
    ports:
      - 127.0.0.1:8072:8050
    networks:
      - computing_api_default

  # ML algorithms
  autoencoders:
    image: ghcr.io/mlexchange/mlex_pytorch_autoencoders:main

  classifier:
    image: ghcr.io/mlexchange/mlex_image_classification:main


networks:
  computing_api_default:
    external: true
